language: python
python: 3.6

install:
  - pip install Lektor
  - mkdir -p ../output
  - lektor build --output-path ../output
  - git rm -rf .
  - cp -r ../output/* .
  - git checkout --orphan master
  - echo "dataforgood.no" > CNAME
  - git add *
  - git -c user.name="D4G bot" -c user.email="No email" commit -am init 
  - git push --force https://$LEKTOR_DEPLOY_USERNAME:$LEKTOR_DEPLOY_PASSWORD@github.com/$TRAVIS_REPO_SLUG master
